### ISSUE TITLE
ResourceInfo Linking Panic in terraform-provider-vsphere

### ISSUE THREAD

**Issue by bflad** [bflad/tfproviderlint#166]
## Version

```
tfproviderlint v0.15.0-dev
```

## Steps to Reproduce

```console
$ git clone git@github.com:terraform-providers/terraform-provider-vsphere.git
$ cd terraform-provider-vsphere
$ tfproviderlint -R003 ./...
```

## Stacktrace

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a198d0]

goroutine 4673 [running]:
github.com/bflad/tfproviderlint/helper/terraformtype/helper/schema.NewResourceInfo(0xc002b1c9c0, 0xc00325c820, 0xc003e53d01)
	/Users/bflad/src/github.com/bflad/tfproviderlint/helper/terraformtype/helper/schema/type_resource.go:62 +0x280
github.com/bflad/tfproviderlint/passes/helper/schema/resourceinfo.run.func1(0x2034e20, 0xc002b1c9c0)
	/Users/bflad/src/github.com/bflad/tfproviderlint/passes/helper/schema/resourceinfo/resourceinfo.go:37 +0x82
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc003e53a60, 0xc003938b08, 0x1, 0x1, 0xc003938b30)
	/Users/bflad/go/pkg/mod/golang.org/x/tools@v0.0.0-20200414001008-ae52e4b55789/go/ast/inspector/inspector.go:77 +0x9f
github.com/bflad/tfproviderlint/passes/helper/schema/resourceinfo.run(0xc0000f83c0, 0xc0000f83c0, 0x0, 0x0, 0x0)
	/Users/bflad/src/github.com/bflad/tfproviderlint/passes/helper/schema/resourceinfo/resourceinfo.go:30 +0xef
golang.org/x/tools/go/analysis/internal/checker.(*action).execOnce(0xc003ecf720)
	/Users/bflad/go/pkg/mod/golang.org/x/tools@v0.0.0-20200414001008-ae52e4b55789/go/analysis/internal/checker/checker.go:690 +0x83a
```

## References

- https://github.com/bflad/tfproviderlint/pull/129
- https://github.com/bflad/tfproviderlint/blob/0dd4d5871e9209bd6e6fd9bce58dde124dc9f206/helper/terraformtype/helper/schema/type_resource.go#L62

**Comment by bflad** [comment]
Likely culprits: https://github.com/terraform-providers/terraform-provider-vsphere/blob/814e5f2acbb00efe01e2441a2995fbc53c9c3609/vsphere/resource_vsphere_compute_cluster.go#L461-L462
