### ISSUE TITLE
R003 crashes on cloudflare-terraform-provider

### ISSUE THREAD

**Issue by jacobbednarz** [bflad/tfproviderlint#223]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### tfproviderlint and terraform-plugin-sdk Version

```console
$ docker run -v (pwd):/src bflad/tfproviderlint:0.21 --version
tfproviderlint v0.21.0

$ go mod graph | cut -d' ' -f 1 | grep terraform-plugin-sdk | uniq
github.com/hashicorp/terraform-plugin-sdk@v1.16.0
```

### Affected Check(s) or Function(s)

* R003
* R011
* R012
* All S checks

### Expected Behavior

Lints should have completed either successfully or unsuccessfully

### Actual Behavior

```
panic: interface conversion: ast.Expr is *ast.Ident, not *ast.CompositeLit

goroutine 4517 [running]:
github.com/bflad/tfproviderlint/helper/terraformtype/helper/schema.NewSchemaInfo(0xc0001a8700, 0xc001d1e370, 0xc0044386d0)
	/home/runner/work/tfproviderlint/tfproviderlint/helper/terraformtype/helper/schema/type_schema.go:211 +0x12e6
github.com/bflad/tfproviderlint/helper/terraformtype/helper/schema.NewResourceInfo(0xc0001a8d00, 0xc001d1e370, 0xc004428801)
	/home/runner/work/tfproviderlint/tfproviderlint/helper/terraformtype/helper/schema/type_resource.go:90 +0x308
github.com/bflad/tfproviderlint/passes/helper/schema/resourceinfo.run.func1(0x852ba0, 0xc0001a8d00)
	/home/runner/work/tfproviderlint/tfproviderlint/passes/helper/schema/resourceinfo/resourceinfo.go:37 +0x82
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc001a60ac0, 0xc0019aeb08, 0x1, 0x1, 0xc001513b30)
	/home/runner/work/tfproviderlint/tfproviderlint/vendor/golang.org/x/tools/go/ast/inspector/inspector.go:77 +0x9f
github.com/bflad/tfproviderlint/passes/helper/schema/resourceinfo.run(0xc0003df740, 0xc0003df740, 0x0, 0x0, 0x0)
	/home/runner/work/tfproviderlint/tfproviderlint/passes/helper/schema/resourceinfo/resourceinfo.go:30 +0xef
golang.org/x/tools/go/analysis/internal/checker.(*action).execOnce(0xc0014d5040)
	/home/runner/work/tfproviderlint/tfproviderlint/vendor/golang.org/x/tools/go/analysis/internal/checker/checker.go:690 +0x83a
sync.(*Once).doSlow(0xc0014d5040, 0xc0000c2f90)
	/opt/hostedtoolcache/go/1.14.12/x64/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/opt/hostedtoolcache/go/1.14.12/x64/src/sync/once.go:57
golang.org/x/tools/go/analysis/internal/checker.(*action).exec(0xc0014d5040)
	/home/runner/work/tfproviderlint/tfproviderlint/vendor/golang.org/x/tools/go/analysis/internal/checker/checker.go:579 +0x60
golang.org/x/tools/go/analysis/internal/checker.execAll.func1(0xc0014d5040)
	/home/runner/work/tfproviderlint/tfproviderlint/vendor/golang.org/x/tools/go/analysis/internal/checker/checker.go:567 +0x34
created by golang.org/x/tools/go/analysis/internal/checker.execAll
	/home/runner/work/tfproviderlint/tfproviderlint/vendor/golang.org/x/tools/go/analysis/internal/checker/checker.go:573 +0x1
```

### References

n/a

### Steps to reproduce

- Clone `github.com/cloudflare/terraform-provider-cloudflare`
- `docker run -v $(pwd):/src bflad/tfproviderlint:0.21 -R003 -R011 -R012 ./cloudflare` in the top directory
- Experience the Go panic

**Comment by bflad** [comment]
Hi @jacobbednarz 👋  Thank you for reporting this and sorry you ran into trouble here. I will take a look into this today and hopefully push out a fix.
